.github/workflows/rust.yml

Tests whether build is done successfully on pull request and push.

Create a Github Action which tests build

---

README.md

docs: change typo of step3 of How to build of MAC

---

game/src/game/display_result.rs
game/src/game/game_player/game_result.rs
game/src/game/game_player/timing_judge.rs

init health calculated by : `let max_health = all_note_count as u64 * 100;`
health increase and decrease by :
```go
NoteAccuracy::Overchaos => {
self.health += 400;
}
NoteAccuracy::Perfect => {
self.health += 200;
}
NoteAccuracy::Great => {
self.health += 100;
}
NoteAccuracy::Good => {
}
NoteAccuracy::Bad => {
self.health -= 100;
}
NoteAccuracy::Miss => {
self.health -= 200;
}
```
score calculated by : `self.score += ((f64::abs(160.0 - difference_abs.clamp(10, 160) as f64) / 150.0) * 1000.0) as u64;`

Bid 46  score and health calculate logic

---

game/src/game/game_player/draw_gameplay_ui.rs

adjust draw_gameplay_ui.rs right_stick_note_height 80 to 90

fix: adjust draw_gameplay_ui.rs right_stick_note_height 80 to 90

---

game/src/game/init.rs

Fixes a flickering bug on Mac OS

Enable VSync

---

game/src/game/common.rs
game/src/game/display_result.rs
game/src/game/game_common_context.rs
game/src/game/init.rs

Use globally initialized ttf_context

---

game/src/game/game_player.rs
game/src/game/game_player/render_video.rs

Video decoding is processed on separated thread

Video decoding on separated thread

---

Cargo.toml
game/Cargo.toml
game/src/game/game_player.rs
game/src/game/game_player/judge_and_display_notes.rs
game/src/game/game_player/render_video.rs
game/src/game/tutorial/learn_stick_note.rs

- Fix freezing bug when too many key inputs are provided burstly
- Fix freezing bug due to too many decoded video frames in buffer

Fix freezing bug while playing the game

---

Cargo.lock
Cargo.toml
chart-recorder/Cargo.toml
chart-recorder/beep_sounds/100Hz.mp3
chart-recorder/beep_sounds/10kHz.mp3
chart-recorder/beep_sounds/1kHz.mp3
chart-recorder/beep_sounds/250hz.mp3
chart-recorder/beep_sounds/440hz.mp3
chart-recorder/src/beep_boop.rs
chart-recorder/src/janggu_state_with_tick.rs
chart-recorder/src/main.rs
data-struct-lib/src/song.rs

Makes simple chart-recording program (with simple beep-boop input delay measurement feature)

Make simple chart recording program

---

game/src/game/display_result.rs
game/src/game/game_player/game_result.rs
game/src/game/game_player/timing_judge.rs

fix combo reset bug while playing
by save max_combo before resetting combo when bad and miss note

fix: combo reset bug while playing

---

.github/workflows/linux-build.yml
.github/workflows/win-build.yml

It works as you can see [here](https://github.com/cau-overchaos/bidrum/actions/runs/9140808851).

Create github action to test building on windows

---

README.md

Adds Windows build instructions using GNU toolchain.

Add Windows build instructions

---

game/src/game/tutorial.rs
game/src/game/util/confirm_dialog.rs

https://github.com/cau-overchaos/bidrum/assets/12497886/dd08eeab-8624-4efb-9f99-8999124a269a

Simple fade-in/fade-out effect for tutorial dialog

---

README.md

- Specified FFmpeg version to 7.* in build instructions
- Added a note about libclang (due to Raspberry Pi)

Specify FFmpeg version and add note on libclang-*

---

.github/workflows/linux-build.yml
.github/workflows/win-build.yml
README.md
game/Cargo.toml

sdl2-mixer is not used anywhere, therefore remove its dependency

Remove sdl2-mixer dependency

---

.github/workflows/linux-build.yml
.github/workflows/win-build.yml
Cargo.lock
README.md
game/Cargo.toml
game/src/game/common.rs
game/src/game/display_result.rs
game/src/game/game_common_context.rs
game/src/game/game_player/effect_sound_player.rs
game/src/game/init.rs
game/src/game/select_song.rs
game/src/game/title.rs
game/src/game/util/confirm_dialog.rs
game/src/game/util/create_outlined_font_texture.rs

I hope it will reduce lifetime/ownership issues because freetype fonts can be cloned.

Use cairo for font rendering instead of sdl2-ttf

---

game/src/game/game_player/timing_judge.rs

typo, proceseed -> processed

---

game/src/game/select_song.rs

* hit 궁편 means pressing left arrow, hit 열편 means pressing right arrow, hit 궁편 and 열편 means seleceting song.
It would be good for  @firekann  to test with janggu.

janggu input when selecting song

---

controller/controller.ino

* Add coin machine code to controller.ino

feat: add coin machine code

---

game/src/game/title.rs

Hit janggu instead of pressing enter key on title screen

Use janggu control on title screen

---

game/src/game/display_result.rs
game/src/game/game_player/chart_player.rs
game/src/game/game_player/chart_player_ui.rs

Add perodic guidelines on note background to indicate beat

Add guidelines for beat

---

game/src/game/game_player/effect_sound_player.rs

feat: change volume

---

game/src/controller_wrapper.rs

Fixes delayed input bug by removing use of lock in controller wrapper

Fix controller input delay bug
